### ISSUE TITLE
release versions and the layout of this package

### ISSUE THREAD

**Issue by kosack** [cta-observatory/cta-conda-recipes#1]
In order to be able to re-produce old releases, we need a way to keep track of a conda build script for each package and for each release of that package.  Should we:

- just keep tags of this repo for each release?
- make a new directory for each release in this repo (e.g. `pyhessio-v1.0.1.conda/`, `pyhessio-2.0.0.conda/`) so that all past versions are in one place?

**Comment by jacquemier** [comment]
I prefer the second solution. Even if it is not really git phylosophie,  It will be easier to re-produce old releases.

**Comment by kosack** [comment]
Agreed, so we can start naming each sub-dir by the release. That will make it easier to rebuild old releases when necessary.
